= TTE -- Toy Transaction Engine
:icons: font
:source-highlighter: pygments
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Tim Weaver
2022/03/21

This is a command line tool that reads a CSV file containing a series of
transactions and generates an accounts balance output file also in CSV.

.The Goals
* Update client accounts
* Handle disputes
* Handle chargebacks
* Ouput the state of clients accounts

.Stretch Goal
* Learn to spell withdrawal (p.s. it's not withdrawl)


== Running

    cargo run -- transactions.csv > accounts.csv

== Input and Output Data

=== Input
The input is a CSV formatted file similar to the following example

.Example Transactions Input Data
[source,csv]
----
type,       client,     tx,     amount
deposit,         1,     1,         1.0
deposit,         2,     2,         2.0
deposit,         1,     3,         2.0
withdrawal,      1,     4,         1.5
withdrawal,      2,     5,         3.0
----

NOTE: *ASSUMPTION* -- There *is* a header line in the CSV file.

NOTE: *ASSUMPTION* -- One can dispute a withdrawal which can cause a negative total which
would mean that the bank owes the client for funds withdrawn fraudulently.

.Transaction Types
* Deposit
* Withdrawal
* Dispute
* Resolve
* Chargeback

=== Output

The output from running the program on a given set of input data is an account
balance summary like this.

.Example Accounts Output Data
[source,csv]
----
client, available, held, total, locked
     1,       1.5,  0.0,   1.5,  false
     2,       2.0,  0.0,   2.0,  false
----

The output is also valid CSV, but is written to stdout instead of to a file.

== Errors
Most errors are silently handled so they don't stop the processing of the
transaction data. Logging is used to note any errors in the transactions file
like referencing tx values that haven't been seen yet.
