= TTE -- Toy Transaction Engine
:icons: font
:source-highlighter: pygments
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Tim Weaver
2022/03/21

This is a command line tool that reads a CSV file containing a series of
transactions and generates an accounts balance output file also in CSV.

.The goals are
* Update client accounts
* Handle disputes
* Handle chargebacks
* Ouput the state of clients accounts


== Running

    cargo run -- transactions.csv > accounts.csv

== Input and Output Data

=== Input
The input is a CSV formatted file similar to the following example

.Example Transactions Input Data
[source,csv]
----
type,       client,     tx,     amount
deposit,         1,     1,         1.0
deposit,         2,     2,         2.0
deposit,         1,     3,         2.0
withdrawal,      1,     4,         1.5
withdrawal,      2,     5,         3.0
----

IMPORTANT: The assumption is that there *may not* be a header line in the CSV file
that will be skipped when parsing. To avoid missing a transaction by always
skipping the first line in a CSV we'll try to parse the line and if it returns
an Error we can log that error but carry on.

.Transaction Types
* Deposit
* Withdrawl
* Dispute
* Resolve
* Chargeback

=== Output

The output from running the program on a given set of input data is an account
balance summary like this.

.Example Accounts Output Data
[source,csv]
----
client, available, held, total, locked
     1,       1.5,  0.0,   1.5,  false
     2,       2.0,  0.0,   2.0,  false
----

The output is also valid CSV, but is written to stdout instead of to a file.
